CREATE VIEW VIEW_USER_INFORMATION AS
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, T1.CITY_NAME AS CURRENT_CITY, T1.STATE_NAME AS CURRENT_STATE, T1.COUNTRY_NAME AS CURRENT_COUNTRY, T2.CITY_NAME AS HOMETOWN_CITY, T2.STATE_NAME AS HOMETOWN_STATE, T2.COUNTRY_NAME AS HOMETOWN_COUNTRY,P.INSTITUTION AS INSTITUTION_NAME, E.PROGRAM_YEAR,P.CONCENTRATION AS PROGRAM_CONCENTRATION, P.DEGREE AS PROGRAM_DEGREE 
FROM USERS U
LEFT JOIN USER_CURRENT_CITIES C ON U.USER_ID = C.USER_ID 
LEFT JOIN CITIES T1 ON T1.CITY_ID = C.CURRENT_CITY_ID
LEFT JOIN USER_HOMETOWN_CITIES H ON U.USER_ID = H.USER_ID 
LEFT JOIN CITIES T2 ON H.HOMETOWN_CITY_ID = T2.CITY_ID
LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID 
LEFT JOIN PROGRAMS P ON E.PROGRAM_ID = P.PROGRAM_ID;


CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT U.USER1_ID, U.USER2_ID
FROM FRIENDS U;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, 
					A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, 
					A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, 
					P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, 
					P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUMS A, PHOTOS P
WHERE  A.ALBUM_ID = P.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT U.EVENT_ID, U.EVENT_CREATOR_ID, U.EVENT_NAME, U.EVENT_TAGLINE, 
					U.EVENT_DESCRIPTION, U.EVENT_HOST, U.EVENT_TYPE, 
					U.EVENT_SUBTYPE, U.EVENT_ADDRESS, C.CITY_NAME AS EVENT_CITY, 
					C.STATE_NAME AS EVENT_STATE, C.COUNTRY_NAME AS EVENT_COUNTRY, U.EVENT_START_TIME,
					U.EVENT_END_TIME
FROM USER_EVENTS U, CITIES C
WHERE U.EVENT_CITY_ID = C.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT T.TAG_PHOTO_ID AS PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, 
					T.TAG_X AS TAG_X_COORDINATE, T.TAG_Y AS TAG_Y_COORDINATE
FROM TAGS T
INNER JOIN PHOTOS P ON T.TAG_PHOTO_ID = P.PHOTO_ID;
