INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, 
						MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, 
						MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM jsoren.PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDS(USER1_ID, USER2_ID)
SELECT DISTINCT T.COL1, T.COL2 FROM (
SELECT P1.USER1_ID AS COL1, P1.USER2_ID AS COL2
FROM jsoren.PUBLIC_ARE_FRIENDS P1
UNION
SELECT P2.USER2_ID, P2.USER1_ID
FROM jsoren.PUBLIC_ARE_FRIENDS P2) T
WHERE T.COL1 - T.COL2 < 0;


--SELECT DISTINCT USER1_ID, USER2_ID
--FROM jsoren.PUBLIC_ARE_FRIENDS;

INSERT INTO CITIES(CITY_NAME, STATE_NAME, COUNTRY_NAME)
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION
where CURRENT_CITY IS NOT NULL
UNION 
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
FROM jsoren.PUBLIC_USER_INFORMATION
where HOMETOWN_CITY IS NOT NULL
UNION
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY  
FROM jsoren.PUBLIC_EVENT_INFORMATION;

INSERT INTO USER_CURRENT_CITIES(USER_ID, CURRENT_CITY_ID)
SELECT DISTINCT U.USER_ID, C.CITY_ID
FROM jsoren.PUBLIC_USER_INFORMATION U,CITIES C
where U.CURRENT_CITY = C.CITY_NAME AND
   U.CURRENT_STATE = C.STATE_NAME AND
   U.CURRENT_COUNTRY = C.COUNTRY_NAME AND
   U.CURRENT_CITY IS NOT NULL;

INSERT INTO USER_HOMETOWN_CITIES(USER_ID, HOMETOWN_CITY_ID)
SELECT DISTINCT H.USER_ID, C.CITY_ID
FROM jsoren.PUBLIC_USER_INFORMATION H,CITIES C
where H.HOMETOWN_CITY = C.CITY_NAME AND
   H.HOMETOWN_STATE = C.STATE_NAME AND
   H.HOMETOWN_COUNTRY = C.COUNTRY_NAME AND
   H.HOMETOWN_CITY IS NOT NULL;

INSERT INTO PROGRAMS(INSTITUTION, CONCENTRATION, DEGREE)
SELECT DISTINCT INSTITUTION_NAME, PROGRAM_CONCENTRATION, PROGRAM_DEGREE
FROM jsoren.PUBLIC_USER_INFORMATION
where INSTITUTION_NAME IS NOT NULL;

INSERT INTO EDUCATION(USER_ID, PROGRAM_ID, PROGRAM_YEAR)
SELECT DISTINCT E.USER_ID,P.PROGRAM_ID,E.PROGRAM_YEAR 
FROM jsoren.PUBLIC_USER_INFORMATION E, PROGRAMS P
where P.INSTITUTION = E.INSTITUTION_NAME and
      P.CONCENTRATION = E.PROGRAM_CONCENTRATION and 
      P.DEGREE = E.PROGRAM_DEGREE and
      E.INSTITUTION_NAME IS NOT NULL;

INSERT INTO USER_EVENTS(EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE,EVENT_DESCRIPTION,
			EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY_ID,
			EVENT_START_TIME, EVENT_END_TIME)
SELECT DISTINCT EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE,E.EVENT_DESCRIPTION,
			E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_ID,
			E.EVENT_START_TIME, E.EVENT_END_TIME
FROM jsoren.PUBLIC_EVENT_INFORMATION E, CITIES C
WHERE E.EVENT_CITY = C.CITY_NAME AND
      E.EVENT_STATE = C.STATE_NAME AND
      E.EVENT_COUNTRY = C.COUNTRY_NAME;

INSERT INTO ALBUMS(ALBUM_ID, ALBUM_OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME,
		   ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID)
SELECT DISTINCT ALBUM_ID, OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME,
		   ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID
FROM jsoren.PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOS(PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME,
	           PHOTO_LINK)
SELECT DISTINCT PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME,
	           PHOTO_LINK
FROM jsoren.PUBLIC_PHOTO_INFORMATION;

INSERT INTO TAGS(TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y)
SELECT DISTINCT PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE  
FROM jsoren.PUBLIC_TAG_INFORMATION;
